/**
 * Nationalities list (English).
 * Egyptian is the default / first entry.
 */
export function useNationalities() {
    const nationalities = [
        'Egyptian',
        'Saudi',
        'Emirati',
        'Kuwaiti',
        'Qatari',
        'Bahraini',
        'Omani',
        'Jordanian',
        'Lebanese',
        'Syrian',
        'Iraqi',
        'Palestinian',
        'Yemeni',
        'Libyan',
        'Tunisian',
        'Algerian',
        'Moroccan',
        'Sudanese',
        'Somali',
        'Afghan',
        'Albanian',
        'American',
        'Argentinian',
        'Australian',
        'Austrian',
        'Bangladeshi',
        'Belgian',
        'Brazilian',
        'British',
        'Bulgarian',
        'Canadian',
        'Chilean',
        'Chinese',
        'Colombian',
        'Croatian',
        'Cuban',
        'Czech',
        'Danish',
        'Dutch',
        'Ethiopian',
        'Filipino',
        'Finnish',
        'French',
        'German',
        'Greek',
        'Hungarian',
        'Indian',
        'Indonesian',
        'Iranian',
        'Irish',
        'Italian',
        'Japanese',
        'Kenyan',
        'Korean',
        'Malaysian',
        'Mexican',
        'New Zealander',
        'Nigerian',
        'Norwegian',
        'Pakistani',
        'Peruvian',
        'Polish',
        'Portuguese',
        'Romanian',
        'Russian',
        'Serbian',
        'Singaporean',
        'South African',
        'Spanish',
        'Sri Lankan',
        'Swedish',
        'Swiss',
        'Thai',
        'Turkish',
        'Ukrainian',
        'Venezuelan',
        'Vietnamese',
    ];

    return { nationalities };
}
