<?php

namespace App\Http\Controllers\Patient;

use App\Jobs\SendSmsJob;
use App\Models\DiscountCode;
use App\Models\LoyaltyPoint;
use App\Models\Setting;
use App\Models\SmsTemplate;
use App\Notifications\LoyaltyRedemptionEmail;
use App\Services\AuditLogger;
use App\Services\LoyaltyService;
use App\Services\SmsService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Notification;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Full-page view of a patient's loyalty ledger:
 * balance, EGP equivalent, redemption rules, full transaction history.
 */
class PatientLoyaltyController extends BasePatientController
{
    public function index(Request $request): Response
    {
        $patient = $this->patient($request);

        $balance = LoyaltyService::balance($patient);
        $minRedeem = (int) Setting::get('loyalty_min_redeem_points', 100);
        $perEgp    = (float) Setting::get('loyalty_points_per_egp', 1);
        $perVisit  = (int)   Setting::get('loyalty_points_per_visit', 50);
        $expiry    = (int)   Setting::get('loyalty_expiry_months', 12);

        $transactions = LoyaltyPoint::where('patient_id', $patient->id)
            ->orderByDesc('created_at')
            ->paginate(20)
            ->through(fn ($r) => [
                'id'          => $r->id,
                'points'      => $r->points,
                'type'        => $r->type,
                'description' => $r->description,
                'expires_at'  => $r->expires_at?->toDateString(),
                'created_at'  => $r->created_at?->toDateTimeString(),
            ]);

        // Active loyalty discount codes (LOYAL-* generated by this patient,
        // not yet used and not yet expired). Pulled from the morph link on
        // the redeem ledger row so we never lean on a fragile prefix match.
        $activeCodeIds = LoyaltyPoint::where('patient_id', $patient->id)
            ->where('type', LoyaltyPoint::TYPE_REDEEM)
            ->where('reference_type', (new DiscountCode)->getMorphClass())
            ->pluck('reference_id')
            ->all();

        $activeCodes = DiscountCode::whereIn('id', $activeCodeIds)
            ->where('is_active', true)
            ->whereColumn('used_count', '<', 'max_uses')
            ->where(function ($q) { $q->whereNull('end_date')->orWhere('end_date', '>=', now()); })
            ->orderByDesc('created_at')
            ->get(['id', 'code', 'discount_value', 'discount_type', 'end_date'])
            ->map(fn ($d) => [
                'code'         => $d->code,
                'amount'       => (float) $d->discount_value,
                'expires_at'   => $d->end_date?->toDateString(),
            ]);

        // Per-type aggregate (sum of positive points by type) for the stat cards.
        $stats = [
            'total_earned'   => (int) LoyaltyPoint::where('patient_id', $patient->id)
                                  ->where('type', LoyaltyPoint::TYPE_EARN)->sum('points'),
            'total_redeemed' => (int) abs(LoyaltyPoint::where('patient_id', $patient->id)
                                  ->where('type', LoyaltyPoint::TYPE_REDEEM)->sum('points')),
            'total_expired'  => (int) abs(LoyaltyPoint::where('patient_id', $patient->id)
                                  ->where('type', LoyaltyPoint::TYPE_EXPIRE)->sum('points')),
        ];

        return Inertia::render('Patient/Loyalty/Index', [
            'balance'      => $balance,
            'egp_value'    => LoyaltyService::pointsToEgp($balance),
            'currency'     => Setting::get('currency_code', 'EGP'),
            'min_redeem'   => $minRedeem,
            'rules' => [
                'points_per_egp'   => $perEgp,
                'points_per_visit' => $perVisit,
                'expiry_months'    => $expiry,
                'redeem_rate'      => (float) Setting::get('loyalty_redeem_rate', 0.10),
            ],
            'stats'        => $stats,
            'transactions' => $transactions,
            'activeCodes'  => $activeCodes,
        ]);
    }

    /**
     * Patient redeems N points → backend mints a single-use discount code
     * valid for 30 days. Code is shown on the dashboard AND emailed to
     * the patient (best-effort) so they don't lose it if they close the tab.
     */
    public function redeem(Request $request): RedirectResponse
    {
        $patient = $this->patient($request);

        $minRedeem = (int) Setting::get('loyalty_min_redeem_points', 100);

        $data = $request->validate([
            'points' => "required|integer|min:$minRedeem",
        ]);

        $result = LoyaltyService::redeemForCode($patient, (int) $data['points']);

        if (!$result) {
            return back()->withErrors(['points' => 'Insufficient balance or invalid amount.']);
        }

        AuditLogger::log('loyalty_redeemed', $patient, [
            'points' => (int) $data['points'],
            'code'   => $result['code'],
            'amount' => $result['amount'],
        ]);

        // Email the code to the patient so they don't lose it (honors the
        // notify_email_bookings preference; treat redemption as transactional).
        if (($patient->email ?? null) && $patient->wantsNotification('bookings', 'email')) {
            try {
                Notification::route('mail', $patient->email)
                    ->notify(new LoyaltyRedemptionEmail(
                        $patient,
                        $result['code'],
                        (float) $result['amount'],
                        (int) $data['points'],
                        $result['expires_at']->toDateString(),
                    ));
            } catch (\Throwable $e) {
                Log::warning('[loyalty.redeem.email] failed', [
                    'patient_id' => $patient->id,
                    'error'      => $e->getMessage(),
                ]);
                // Don't fail the redemption — patient still sees the code on screen.
            }
        }

        // Best-effort SMS confirmation with the code (so patient has it
        // both via email AND a copy on their phone).
        $this->sendRedeemedSms($patient, (int) $data['points'], $result);

        return back()->with('redemption', [
            'code'       => $result['code'],
            'amount'     => $result['amount'],
            'expires_at' => $result['expires_at']->toDateString(),
        ]);
    }

    private function sendRedeemedSms($patient, int $points, array $result): void
    {
        try {
            if (! SmsService::isEnabled()) return;
            if (! $patient->phone) return;
            if (! $patient->wantsNotification('bookings', 'sms')) return;
            if (Setting::get('sms_on_loyalty_redeemed', '1') !== '1') return;

            $currency = Setting::get('currency_code', 'EGP');
            $locale   = $patient->preferred_language ?? 'ar';

            $body = SmsTemplate::render('loyalty_redeemed', [
                'points'     => $points,
                'code'       => $result['code'],
                'amount'     => number_format((float) $result['amount'], 0) . ' ' . $currency,
                'expires_at' => $result['expires_at']->toDateString(),
            ], $locale);

            if (! $body) return;

            SendSmsJob::dispatch($patient->phone, $body, null, 'loyalty_redeemed');
        } catch (\Throwable $e) {
            Log::warning('[loyalty.redeemed.sms] failed', [
                'patient_id' => $patient->id ?? null,
                'error'      => $e->getMessage(),
            ]);
        }
    }
}
